---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint
    commands:
      - yamllint -d relaxed .drone.yml

  - name: gotest
    depends_on:
      - yamllint
    image: golang:1.14
    commands:
      - cd pkg/helloworld
      - go test

  - name: build
    depends_on:
      - gotest
    image: golang:1.14
    environment:
      CGO_ENABLED: "0"
    commands:
      - cd cmd/helloworld
      - go build -o helloworld

  - name: run
    depends_on:
      - build
    image: curlimages/curl:7.70.0
    environment:
      PORT: "8080"
    commands:
      - cd cmd/helloworld
      - ./helloworld &
      - curl -v http://127.0.0.1:8080
